name: Deploy CI/CD to Develop

on:
  push: # tells github to run this on any push to the repository
    branches:
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy to dev
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEV_KEY }}
        port: 22
        script: |
          sudo -u frappe -H bash -c "
            cd /home/frappe/frappe-bench/apps/beams # we move into our app's folder
            git pull upstream develop # we pull any changes from git
            cd /home/frappe          
            cd /home/frappe/frappe-bench
            # bench setup requirements
            bench migrate # sync database
          "
          sudo supervisorctl restart all
